# Generated by Django 6.0.1 on 2026-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendance',
            name='day_status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
