# Generated by Django 6.0.1 on 2026-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainerattendance_day_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('training', 'Training / Class'), ('other', 'Other Activity')], default='training', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
