# Generated by Django 5.2.13 on 2026-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_batch_batch_type_batch_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('weekoff', 'Week Off'), ('optional_holiday', 'Optional Holiday'), ('mandatory_holiday', 'Mandatory Holiday'), ('other', 'Other')], default='casual', max_length=30),
        ),
    ]
